import { createFileRoute, redirect } from "@tanstack/react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { format } from "date-fns";
import { CalendarPlus, Pencil, Trash2 } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { useCurrentUser, hasAny } from "@/hooks/useCurrentUser";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";

export const Route = createFileRoute("/_authenticated/events")({ beforeLoad: async () => { if (!(await supabase.auth.getUser()).data.user) throw redirect({ to: "/auth" }); }, component: EventsPage });
type Draft = { id?: string; title: string; event_type: string; start_date: string; end_date: string; description: string };
const blank = (): Draft => ({ title: "", event_type: "event", start_date: format(new Date(), "yyyy-MM-dd"), end_date: "", description: "" });
function EventsPage() {
  const { data: me } = useCurrentUser(); const schoolId = me?.profile?.school_id; const qc = useQueryClient(); const [draft, setDraft] = useState<Draft>(blank()); const canManage = hasAny(me?.roles, ["school_admin", "head_teacher", "deputy_head_teacher"]);
  const { data: events = [] } = useQuery({ queryKey: ["school-events", schoolId], enabled: !!schoolId, queryFn: async () => { const { data, error } = await supabase.from("school_events").select("*").order("start_date"); if (error) throw error; return data ?? []; } });
  const save = useMutation({ mutationFn: async (value: Draft) => { const payload = { title: value.title.trim(), event_type: value.event_type, start_date: value.start_date, end_date: value.end_date || null, description: value.description.trim() || null, school_id: schoolId! }; const result = value.id ? await supabase.from("school_events").update(payload).eq("id", value.id) : await supabase.from("school_events").insert(payload); if (result.error) throw result.error; const { data: users, error: usersError } = await supabase.from("profiles").select("id").eq("school_id", schoolId!); if (usersError) throw usersError; if (users?.length) { const dateText = value.end_date ? `${value.start_date} – ${value.end_date}` : value.start_date; const { error } = await supabase.from("notifications").insert(users.map((user) => ({ school_id: schoolId!, user_id: user.id, title: value.id ? "School event updated" : "New school event", body: `${value.title.trim()} is scheduled for ${dateText}.` }))); if (error) throw error; } }, onSuccess: () => { qc.invalidateQueries({ queryKey: ["school-events"] }); setDraft(blank()); toast.success("Event saved and users notified"); }, onError: (e) => toast.error(e.message) });
  const remove = useMutation({ mutationFn: async (id: string) => { const { error } = await supabase.from("school_events").delete().eq("id", id); if (error) throw error; }, onSuccess: () => { qc.invalidateQueries({ queryKey: ["school-events"] }); toast.success("Event deleted"); }, onError: (e) => toast.error(e.message) });
  return <div className="grid gap-5 lg:grid-cols-[minmax(0,1fr)_360px]"><div className="space-y-4"><div><h1 className="text-2xl font-bold">Events</h1><p className="text-sm text-muted-foreground">Create and manage school events, activities, and important dates.</p></div>{events.map((event) => <Card key={event.id}><CardContent className="flex items-start justify-between gap-3 p-4"><div><p className="font-semibold">{event.title}</p><p className="text-sm text-muted-foreground">{event.start_date}{event.end_date ? ` – ${event.end_date}` : ""} · {event.event_type}</p>{event.description && <p className="mt-2 text-sm">{event.description}</p>}</div>{canManage && <div className="flex shrink-0 gap-1"><Button variant="ghost" size="icon" onClick={() => setDraft({ id: event.id, title: event.title, event_type: event.event_type, start_date: event.start_date, end_date: event.end_date ?? "", description: event.description ?? "" })}><Pencil className="h-4 w-4" /></Button><Button variant="ghost" size="icon" onClick={() => remove.mutate(event.id)}><Trash2 className="h-4 w-4 text-destructive" /></Button></div>}</CardContent></Card>)}{!events.length && <Card><CardContent className="p-8 text-center text-muted-foreground">No events yet.</CardContent></Card>}</div>{canManage && <Card className="h-fit"><CardHeader><CardTitle className="flex items-center gap-2"><CalendarPlus className="h-5 w-5" />{draft.id ? "Edit event" : "New event"}</CardTitle></CardHeader><CardContent><form className="space-y-4" onSubmit={(e) => { e.preventDefault(); if (!draft.title.trim()) return toast.error("Enter an event title"); save.mutate(draft); }}><div><Label>Title</Label><Input value={draft.title} onChange={(e) => setDraft({ ...draft, title: e.target.value })} required /></div><div><Label>Type</Label><Input value={draft.event_type} onChange={(e) => setDraft({ ...draft, event_type: e.target.value })} placeholder="Meeting, holiday, exam…" /></div><div className="grid grid-cols-2 gap-3"><div><Label>Start date</Label><Input type="date" value={draft.start_date} onChange={(e) => setDraft({ ...draft, start_date: e.target.value })} required /></div><div><Label>End date</Label><Input type="date" value={draft.end_date} onChange={(e) => setDraft({ ...draft, end_date: e.target.value })} /></div></div><div><Label>Description</Label><Textarea value={draft.description} onChange={(e) => setDraft({ ...draft, description: e.target.value })} rows={4} /></div><div className="flex gap-2"><Button type="submit" disabled={save.isPending}>Save event</Button>{draft.id && <Button type="button" variant="outline" onClick={() => setDraft(blank())}>Cancel</Button>}</div></form></CardContent></Card>}</div>;
}
