/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DashoardRouteImport } from './routes/dashoard'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AuthenticatedAcademicsRouteImport } from './routes/_authenticated/academics'
import { Route as AuthenticatedApprovalRouteImport } from './routes/_authenticated/approval'
import { Route as AuthenticatedApprovedRouteImport } from './routes/_authenticated/approved'
import { Route as AuthenticatedAssessmentsRouteImport } from './routes/_authenticated/assessments'
import { Route as AuthenticatedAssestmentRouteImport } from './routes/_authenticated/assestment'
import { Route as AuthenticatedAttendanceRouteImport } from './routes/_authenticated/attendance'
import { Route as AuthenticatedAuditLogsRouteImport } from './routes/_authenticated/audit-logs'
import { Route as AuthenticatedChangePasswordRouteImport } from './routes/_authenticated/change-password'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedEnvDebugRouteImport } from './routes/_authenticated/env-debug'
import { Route as AuthenticatedFinanceRouteImport } from './routes/_authenticated/finance'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated/library'
import { Route as AuthenticatedMarksheetRouteImport } from './routes/_authenticated/marksheet'
import { Route as AuthenticatedPromotionsRouteImport } from './routes/_authenticated/promotions'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedSchoolsRouteImport } from './routes/_authenticated/schools'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedStudentsRouteImport } from './routes/_authenticated/students'
import { Route as AuthenticatedTimetableRouteImport } from './routes/_authenticated/timetable'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as WebsitePagesIndexRouteImport } from './routes/website-pages/index'
import { Route as WebsitePagesAboutRouteImport } from './routes/website-pages/about'
import { Route as WebsitePagesBlogsRouteImport } from './routes/website-pages/blogs'
import { Route as WebsitePagesContactUsRouteImport } from './routes/website-pages/contact-us'
import { Route as WebsitePagesFeaturesRouteImport } from './routes/website-pages/features'
import { Route as WebsitePagesReportCardSamplesRouteImport } from './routes/website-pages/report-card-samples'
import { Route as WebsitePagesFeaturesSlugRouteImport } from './routes/website-pages/features/$slug'
import { Route as AuthenticatedFinanceKindIdRouteImport } from './routes/_authenticated/finance.$kind.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashoardRoute = DashoardRouteImport.update({
  id: '/dashoard',
  path: '/dashoard',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAcademicsRoute = AuthenticatedAcademicsRouteImport.update({
  id: '/academics',
  path: '/academics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApprovalRoute = AuthenticatedApprovalRouteImport.update({
  id: '/approval',
  path: '/approval',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApprovedRoute = AuthenticatedApprovedRouteImport.update({
  id: '/approved',
  path: '/approved',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssessmentsRoute =
  AuthenticatedAssessmentsRouteImport.update({
    id: '/assessments',
    path: '/assessments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAssestmentRoute = AuthenticatedAssestmentRouteImport.update({
  id: '/assestment',
  path: '/assestment',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAttendanceRoute = AuthenticatedAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditLogsRoute = AuthenticatedAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChangePasswordRoute =
  AuthenticatedChangePasswordRouteImport.update({
    id: '/change-password',
    path: '/change-password',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEnvDebugRoute = AuthenticatedEnvDebugRouteImport.update({
  id: '/env-debug',
  path: '/env-debug',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceRoute = AuthenticatedFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMarksheetRoute = AuthenticatedMarksheetRouteImport.update({
  id: '/marksheet',
  path: '/marksheet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPromotionsRoute = AuthenticatedPromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSchoolsRoute = AuthenticatedSchoolsRouteImport.update({
  id: '/schools',
  path: '/schools',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudentsRoute = AuthenticatedStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTimetableRoute = AuthenticatedTimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const WebsitePagesIndexRoute = WebsitePagesIndexRouteImport.update({
  id: '/website-pages/',
  path: '/website-pages/',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsitePagesAboutRoute = WebsitePagesAboutRouteImport.update({
  id: '/website-pages/about',
  path: '/website-pages/about',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsitePagesBlogsRoute = WebsitePagesBlogsRouteImport.update({
  id: '/website-pages/blogs',
  path: '/website-pages/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsitePagesContactUsRoute = WebsitePagesContactUsRouteImport.update({
  id: '/website-pages/contact-us',
  path: '/website-pages/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsitePagesFeaturesRoute = WebsitePagesFeaturesRouteImport.update({
  id: '/website-pages/features',
  path: '/website-pages/features',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsitePagesReportCardSamplesRoute =
  WebsitePagesReportCardSamplesRouteImport.update({
    id: '/website-pages/report-card-samples',
    path: '/website-pages/report-card-samples',
    getParentRoute: () => rootRouteImport,
  } as any)
const WebsitePagesFeaturesSlugRoute =
  WebsitePagesFeaturesSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => WebsitePagesFeaturesRoute,
  } as any)
const AuthenticatedFinanceKindIdRoute =
  AuthenticatedFinanceKindIdRouteImport.update({
    id: '/$kind/$id',
    path: '/$kind/$id',
    getParentRoute: () => AuthenticatedFinanceRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashoard': typeof DashoardRoute
  '/signup': typeof SignupRoute
  '/academics': typeof AuthenticatedAcademicsRoute
  '/approval': typeof AuthenticatedApprovalRoute
  '/approved': typeof AuthenticatedApprovedRoute
  '/assessments': typeof AuthenticatedAssessmentsRoute
  '/assestment': typeof AuthenticatedAssestmentRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/audit-logs': typeof AuthenticatedAuditLogsRoute
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/env-debug': typeof AuthenticatedEnvDebugRoute
  '/finance': typeof AuthenticatedFinanceRouteWithChildren
  '/library': typeof AuthenticatedLibraryRoute
  '/marksheet': typeof AuthenticatedMarksheetRoute
  '/promotions': typeof AuthenticatedPromotionsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/schools': typeof AuthenticatedSchoolsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/students': typeof AuthenticatedStudentsRoute
  '/timetable': typeof AuthenticatedTimetableRoute
  '/users': typeof AuthenticatedUsersRoute
  '/website-pages/about': typeof WebsitePagesAboutRoute
  '/website-pages/blogs': typeof WebsitePagesBlogsRoute
  '/website-pages/contact-us': typeof WebsitePagesContactUsRoute
  '/website-pages/features': typeof WebsitePagesFeaturesRouteWithChildren
  '/website-pages/report-card-samples': typeof WebsitePagesReportCardSamplesRoute
  '/website-pages/': typeof WebsitePagesIndexRoute
  '/website-pages/features/$slug': typeof WebsitePagesFeaturesSlugRoute
  '/finance/$kind/$id': typeof AuthenticatedFinanceKindIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashoard': typeof DashoardRoute
  '/signup': typeof SignupRoute
  '/academics': typeof AuthenticatedAcademicsRoute
  '/approval': typeof AuthenticatedApprovalRoute
  '/approved': typeof AuthenticatedApprovedRoute
  '/assessments': typeof AuthenticatedAssessmentsRoute
  '/assestment': typeof AuthenticatedAssestmentRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/audit-logs': typeof AuthenticatedAuditLogsRoute
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/env-debug': typeof AuthenticatedEnvDebugRoute
  '/finance': typeof AuthenticatedFinanceRouteWithChildren
  '/library': typeof AuthenticatedLibraryRoute
  '/marksheet': typeof AuthenticatedMarksheetRoute
  '/promotions': typeof AuthenticatedPromotionsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/schools': typeof AuthenticatedSchoolsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/students': typeof AuthenticatedStudentsRoute
  '/timetable': typeof AuthenticatedTimetableRoute
  '/users': typeof AuthenticatedUsersRoute
  '/website-pages/about': typeof WebsitePagesAboutRoute
  '/website-pages/blogs': typeof WebsitePagesBlogsRoute
  '/website-pages/contact-us': typeof WebsitePagesContactUsRoute
  '/website-pages/features': typeof WebsitePagesFeaturesRouteWithChildren
  '/website-pages/report-card-samples': typeof WebsitePagesReportCardSamplesRoute
  '/website-pages': typeof WebsitePagesIndexRoute
  '/website-pages/features/$slug': typeof WebsitePagesFeaturesSlugRoute
  '/finance/$kind/$id': typeof AuthenticatedFinanceKindIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/dashoard': typeof DashoardRoute
  '/signup': typeof SignupRoute
  '/_authenticated/academics': typeof AuthenticatedAcademicsRoute
  '/_authenticated/approval': typeof AuthenticatedApprovalRoute
  '/_authenticated/approved': typeof AuthenticatedApprovedRoute
  '/_authenticated/assessments': typeof AuthenticatedAssessmentsRoute
  '/_authenticated/assestment': typeof AuthenticatedAssestmentRoute
  '/_authenticated/attendance': typeof AuthenticatedAttendanceRoute
  '/_authenticated/audit-logs': typeof AuthenticatedAuditLogsRoute
  '/_authenticated/change-password': typeof AuthenticatedChangePasswordRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/env-debug': typeof AuthenticatedEnvDebugRoute
  '/_authenticated/finance': typeof AuthenticatedFinanceRouteWithChildren
  '/_authenticated/library': typeof AuthenticatedLibraryRoute
  '/_authenticated/marksheet': typeof AuthenticatedMarksheetRoute
  '/_authenticated/promotions': typeof AuthenticatedPromotionsRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/schools': typeof AuthenticatedSchoolsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/students': typeof AuthenticatedStudentsRoute
  '/_authenticated/timetable': typeof AuthenticatedTimetableRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/website-pages/about': typeof WebsitePagesAboutRoute
  '/website-pages/blogs': typeof WebsitePagesBlogsRoute
  '/website-pages/contact-us': typeof WebsitePagesContactUsRoute
  '/website-pages/features': typeof WebsitePagesFeaturesRouteWithChildren
  '/website-pages/report-card-samples': typeof WebsitePagesReportCardSamplesRoute
  '/website-pages/': typeof WebsitePagesIndexRoute
  '/website-pages/features/$slug': typeof WebsitePagesFeaturesSlugRoute
  '/_authenticated/finance/$kind/$id': typeof AuthenticatedFinanceKindIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashoard'
    | '/signup'
    | '/academics'
    | '/approval'
    | '/approved'
    | '/assessments'
    | '/assestment'
    | '/attendance'
    | '/audit-logs'
    | '/change-password'
    | '/dashboard'
    | '/env-debug'
    | '/finance'
    | '/library'
    | '/marksheet'
    | '/promotions'
    | '/reports'
    | '/schools'
    | '/settings'
    | '/students'
    | '/timetable'
    | '/users'
    | '/website-pages/about'
    | '/website-pages/blogs'
    | '/website-pages/contact-us'
    | '/website-pages/features'
    | '/website-pages/report-card-samples'
    | '/website-pages/'
    | '/website-pages/features/$slug'
    | '/finance/$kind/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashoard'
    | '/signup'
    | '/academics'
    | '/approval'
    | '/approved'
    | '/assessments'
    | '/assestment'
    | '/attendance'
    | '/audit-logs'
    | '/change-password'
    | '/dashboard'
    | '/env-debug'
    | '/finance'
    | '/library'
    | '/marksheet'
    | '/promotions'
    | '/reports'
    | '/schools'
    | '/settings'
    | '/students'
    | '/timetable'
    | '/users'
    | '/website-pages/about'
    | '/website-pages/blogs'
    | '/website-pages/contact-us'
    | '/website-pages/features'
    | '/website-pages/report-card-samples'
    | '/website-pages'
    | '/website-pages/features/$slug'
    | '/finance/$kind/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/dashoard'
    | '/signup'
    | '/_authenticated/academics'
    | '/_authenticated/approval'
    | '/_authenticated/approved'
    | '/_authenticated/assessments'
    | '/_authenticated/assestment'
    | '/_authenticated/attendance'
    | '/_authenticated/audit-logs'
    | '/_authenticated/change-password'
    | '/_authenticated/dashboard'
    | '/_authenticated/env-debug'
    | '/_authenticated/finance'
    | '/_authenticated/library'
    | '/_authenticated/marksheet'
    | '/_authenticated/promotions'
    | '/_authenticated/reports'
    | '/_authenticated/schools'
    | '/_authenticated/settings'
    | '/_authenticated/students'
    | '/_authenticated/timetable'
    | '/_authenticated/users'
    | '/website-pages/about'
    | '/website-pages/blogs'
    | '/website-pages/contact-us'
    | '/website-pages/features'
    | '/website-pages/report-card-samples'
    | '/website-pages/'
    | '/website-pages/features/$slug'
    | '/_authenticated/finance/$kind/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DashoardRoute: typeof DashoardRoute
  SignupRoute: typeof SignupRoute
  WebsitePagesAboutRoute: typeof WebsitePagesAboutRoute
  WebsitePagesBlogsRoute: typeof WebsitePagesBlogsRoute
  WebsitePagesContactUsRoute: typeof WebsitePagesContactUsRoute
  WebsitePagesFeaturesRoute: typeof WebsitePagesFeaturesRouteWithChildren
  WebsitePagesReportCardSamplesRoute: typeof WebsitePagesReportCardSamplesRoute
  WebsitePagesIndexRoute: typeof WebsitePagesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashoard': {
      id: '/dashoard'
      path: '/dashoard'
      fullPath: '/dashoard'
      preLoaderRoute: typeof DashoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/academics': {
      id: '/_authenticated/academics'
      path: '/academics'
      fullPath: '/academics'
      preLoaderRoute: typeof AuthenticatedAcademicsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/approval': {
      id: '/_authenticated/approval'
      path: '/approval'
      fullPath: '/approval'
      preLoaderRoute: typeof AuthenticatedApprovalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/approved': {
      id: '/_authenticated/approved'
      path: '/approved'
      fullPath: '/approved'
      preLoaderRoute: typeof AuthenticatedApprovedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assessments': {
      id: '/_authenticated/assessments'
      path: '/assessments'
      fullPath: '/assessments'
      preLoaderRoute: typeof AuthenticatedAssessmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assestment': {
      id: '/_authenticated/assestment'
      path: '/assestment'
      fullPath: '/assestment'
      preLoaderRoute: typeof AuthenticatedAssestmentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attendance': {
      id: '/_authenticated/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AuthenticatedAttendanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit-logs': {
      id: '/_authenticated/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuthenticatedAuditLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/change-password': {
      id: '/_authenticated/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof AuthenticatedChangePasswordRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/env-debug': {
      id: '/_authenticated/env-debug'
      path: '/env-debug'
      fullPath: '/env-debug'
      preLoaderRoute: typeof AuthenticatedEnvDebugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance': {
      id: '/_authenticated/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AuthenticatedFinanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marksheet': {
      id: '/_authenticated/marksheet'
      path: '/marksheet'
      fullPath: '/marksheet'
      preLoaderRoute: typeof AuthenticatedMarksheetRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/promotions': {
      id: '/_authenticated/promotions'
      path: '/promotions'
      fullPath: '/promotions'
      preLoaderRoute: typeof AuthenticatedPromotionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/schools': {
      id: '/_authenticated/schools'
      path: '/schools'
      fullPath: '/schools'
      preLoaderRoute: typeof AuthenticatedSchoolsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/students': {
      id: '/_authenticated/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AuthenticatedStudentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/timetable': {
      id: '/_authenticated/timetable'
      path: '/timetable'
      fullPath: '/timetable'
      preLoaderRoute: typeof AuthenticatedTimetableRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/website-pages/': {
      id: '/website-pages/'
      path: '/website-pages'
      fullPath: '/website-pages/'
      preLoaderRoute: typeof WebsitePagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website-pages/about': {
      id: '/website-pages/about'
      path: '/website-pages/about'
      fullPath: '/website-pages/about'
      preLoaderRoute: typeof WebsitePagesAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website-pages/blogs': {
      id: '/website-pages/blogs'
      path: '/website-pages/blogs'
      fullPath: '/website-pages/blogs'
      preLoaderRoute: typeof WebsitePagesBlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website-pages/contact-us': {
      id: '/website-pages/contact-us'
      path: '/website-pages/contact-us'
      fullPath: '/website-pages/contact-us'
      preLoaderRoute: typeof WebsitePagesContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website-pages/features': {
      id: '/website-pages/features'
      path: '/website-pages/features'
      fullPath: '/website-pages/features'
      preLoaderRoute: typeof WebsitePagesFeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website-pages/report-card-samples': {
      id: '/website-pages/report-card-samples'
      path: '/website-pages/report-card-samples'
      fullPath: '/website-pages/report-card-samples'
      preLoaderRoute: typeof WebsitePagesReportCardSamplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website-pages/features/$slug': {
      id: '/website-pages/features/$slug'
      path: '/$slug'
      fullPath: '/website-pages/features/$slug'
      preLoaderRoute: typeof WebsitePagesFeaturesSlugRouteImport
      parentRoute: typeof WebsitePagesFeaturesRoute
    }
    '/_authenticated/finance/$kind/$id': {
      id: '/_authenticated/finance/$kind/$id'
      path: '/$kind/$id'
      fullPath: '/finance/$kind/$id'
      preLoaderRoute: typeof AuthenticatedFinanceKindIdRouteImport
      parentRoute: typeof AuthenticatedFinanceRoute
    }
  }
}

interface AuthenticatedFinanceRouteChildren {
  AuthenticatedFinanceKindIdRoute: typeof AuthenticatedFinanceKindIdRoute
}

const AuthenticatedFinanceRouteChildren: AuthenticatedFinanceRouteChildren = {
  AuthenticatedFinanceKindIdRoute: AuthenticatedFinanceKindIdRoute,
}

const AuthenticatedFinanceRouteWithChildren =
  AuthenticatedFinanceRoute._addFileChildren(AuthenticatedFinanceRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAcademicsRoute: typeof AuthenticatedAcademicsRoute
  AuthenticatedApprovalRoute: typeof AuthenticatedApprovalRoute
  AuthenticatedApprovedRoute: typeof AuthenticatedApprovedRoute
  AuthenticatedAssessmentsRoute: typeof AuthenticatedAssessmentsRoute
  AuthenticatedAssestmentRoute: typeof AuthenticatedAssestmentRoute
  AuthenticatedAttendanceRoute: typeof AuthenticatedAttendanceRoute
  AuthenticatedAuditLogsRoute: typeof AuthenticatedAuditLogsRoute
  AuthenticatedChangePasswordRoute: typeof AuthenticatedChangePasswordRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEnvDebugRoute: typeof AuthenticatedEnvDebugRoute
  AuthenticatedFinanceRoute: typeof AuthenticatedFinanceRouteWithChildren
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRoute
  AuthenticatedMarksheetRoute: typeof AuthenticatedMarksheetRoute
  AuthenticatedPromotionsRoute: typeof AuthenticatedPromotionsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSchoolsRoute: typeof AuthenticatedSchoolsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStudentsRoute: typeof AuthenticatedStudentsRoute
  AuthenticatedTimetableRoute: typeof AuthenticatedTimetableRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAcademicsRoute: AuthenticatedAcademicsRoute,
  AuthenticatedApprovalRoute: AuthenticatedApprovalRoute,
  AuthenticatedApprovedRoute: AuthenticatedApprovedRoute,
  AuthenticatedAssessmentsRoute: AuthenticatedAssessmentsRoute,
  AuthenticatedAssestmentRoute: AuthenticatedAssestmentRoute,
  AuthenticatedAttendanceRoute: AuthenticatedAttendanceRoute,
  AuthenticatedAuditLogsRoute: AuthenticatedAuditLogsRoute,
  AuthenticatedChangePasswordRoute: AuthenticatedChangePasswordRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEnvDebugRoute: AuthenticatedEnvDebugRoute,
  AuthenticatedFinanceRoute: AuthenticatedFinanceRouteWithChildren,
  AuthenticatedLibraryRoute: AuthenticatedLibraryRoute,
  AuthenticatedMarksheetRoute: AuthenticatedMarksheetRoute,
  AuthenticatedPromotionsRoute: AuthenticatedPromotionsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSchoolsRoute: AuthenticatedSchoolsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStudentsRoute: AuthenticatedStudentsRoute,
  AuthenticatedTimetableRoute: AuthenticatedTimetableRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface WebsitePagesFeaturesRouteChildren {
  WebsitePagesFeaturesSlugRoute: typeof WebsitePagesFeaturesSlugRoute
}

const WebsitePagesFeaturesRouteChildren: WebsitePagesFeaturesRouteChildren = {
  WebsitePagesFeaturesSlugRoute: WebsitePagesFeaturesSlugRoute,
}

const WebsitePagesFeaturesRouteWithChildren =
  WebsitePagesFeaturesRoute._addFileChildren(WebsitePagesFeaturesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DashoardRoute: DashoardRoute,
  SignupRoute: SignupRoute,
  WebsitePagesAboutRoute: WebsitePagesAboutRoute,
  WebsitePagesBlogsRoute: WebsitePagesBlogsRoute,
  WebsitePagesContactUsRoute: WebsitePagesContactUsRoute,
  WebsitePagesFeaturesRoute: WebsitePagesFeaturesRouteWithChildren,
  WebsitePagesReportCardSamplesRoute: WebsitePagesReportCardSamplesRoute,
  WebsitePagesIndexRoute: WebsitePagesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
